sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: glxxbph96o6DOASchqk87rn8UM80mamRyU3tSDqIcEUceKS7LQ09Ym4gOAmpGeSKlxx0gmSrmMrgTsD277N+YH8QYosoyozgKaHOdsWqM0NhUYZSxq/nA6544DsV302pOnHlBlwvZiFnAY3AMVyccRpGk/NAUjtzJ0idPfHw58MfbBo7fbBclrtDcSyKN9QA6fSRjVGzRCfj6TfU+l5PHS4bvWX90nLhZK7tHbsICStqrhdxOAvF8xzPerlVfJYd4wn3E3X6glAXM8+iV22A9lxMO4FGd3NFlb7rF17uM/k3Mg+h39CK9n9ORkbrn7OTfvZgfcwiTKCQXspz+6rFk4L4E2scfOJeyp8BdBU7XYQU44G1jTr7kkFBMGWnp1FuYW3C9npg9mQK84z5fL65LZJVAunenA5aPaFAVazP/20a8VBantIZ0WwWvAaizZ/bQlJ1NM4UCJSC1F6UopIRCRbgfcBkuT2Ktt98IJQGCAEMTbkd6F8B2wVtpoium0zT2rg12Qe44YgYH4OZ8JX07p/BhKIjhJIWXJzh9NUvNP5HrBRcawSVsXyorWHNpCix2PhA7RUEU/TaWjTf0DPiiLtOcP2NL3Wg82mwxN3x8D82SeIhAqRBevXIMI0M+MbXGmCrBhv+VT8TPicNnwoj9lBUIZXdQfe1/4pUyvGLtwA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Christian-Science_3187
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy